apiVersion: v1
kind: Service
metadata:
  name: complete-e2e-deployments
  labels:
    app: complete-e2e-deployments
spec:
  selector:
    app: complete-e2e-deployments
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer